export const genres = {
  acción: 'AC',
  animación: 'AN',
  aventuras: 'AV',
  bélico: 'BE',
  'ciencia ficción': 'C-F',
  'cine negro': 'F-N',
  comedia: 'CO',
  desconocido: 'DESC',
  documental: 'DO',
  drama: 'DR',
  fantástico: 'FAN',
  infantil: 'INF',
  intriga: 'INT',
  musical: 'MU',
  romance: 'RO',
  'serie de tv': 'TV_SE',
  terror: 'TE',
  thriller: 'TH',
  western: 'WE',
};

export const countries = {
  'Todos los países': '',
  Afganistán: 'AF',
  Albania: 'AL',
  Alemania: 'DE',
  'Alemania del Este': 'FD',
  'Alemania del Oeste': 'FF',
  Andorra: 'AD',
  Angola: 'AO',
  'Antigua y Barbuda': 'AG',
  'Arabia Saudí': 'SA',
  Argelia: 'DZ',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrein: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Bélgica: 'BE',
  Belize: 'BZ',
  Benín: 'BJ',
  Bielorrusia: 'BY',
  Bolivia: 'BO',
  'Bosnia y Herzegovina': 'BA',
  Botswana: 'BW',
  Brasil: 'BR',
  Brunei: 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Bután: 'BT',
  'Cabo Verde': 'CV',
  Camboya: 'KH',
  Camerún: 'CM',
  Canadá: 'CA',
  Chad: 'TD',
  Checoslovaquia: 'ZX',
  Chile: 'CL',
  China: 'CN',
  Chipre: 'CY',
  Colombia: 'CO',
  Comores: 'KM',
  Congo: 'CG',
  Corea: 'KK',
  'Corea del Norte': 'KP',
  'Corea del Sur': 'KR',
  'Costa de Marfil': 'CI',
  'Costa Rica': 'CR',
  Croacia: 'HR',
  Cuba: 'CU',
  Dinamarca: 'DK',
  Dominica: 'DM',
  Ecuador: 'EC',
  Egipto: 'EG',
  'El Salvador': 'SV',
  'Emiratos Árabes': 'AE',
  Eritrea: 'ER',
  Eslovaquia: 'SK',
  Eslovenia: 'SI',
  España: 'ES',
  'Estados Unidos': 'US',
  Estonia: 'EE',
  Etiopía: 'ET',
  Fidji: 'FJ',
  Filipinas: 'PH',
  Finlandia: 'FI',
  Francia: 'FR',
  Gabón: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Ghana: 'GH',
  Granada: 'GD',
  Grecia: 'GR',
  Groenlandia: 'GL',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea Bissau': 'GW',
  'Guinea Ecuatorial': 'GQ',
  Guyana: 'GY',
  Haití: 'HT',
  Honduras: 'HN',
  'Hong Kong': 'HK',
  Hungría: 'HU',
  India: 'IN',
  Indonesia: 'ID',
  Irak: 'IQ',
  Irán: 'IR',
  Irlanda: 'IE',
  Islandia: 'IS',
  Israel: 'IL',
  Italia: 'IT',
  Jamaica: 'JM',
  Japón: 'JP',
  Jordania: 'JO',
  Kazajstán: 'KZ',
  Kenia: 'KE',
  Kirguistán: 'KG',
  Kosovo: 'KO',
  Kuwait: 'KW',
  Laos: 'LA',
  Lesotho: 'LS',
  Letonia: 'LE',
  Líbano: 'LB',
  Liberia: 'LR',
  Libia: 'LY',
  Liechtenstein: 'LI',
  Lituania: 'LT',
  Luxemburgo: 'LU',
  Macao: 'MO',
  Macedonia: 'MK',
  Madagascar: 'MG',
  Malasia: 'MY',
  Malawi: 'MW',
  Maldivas: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  Marruecos: 'MA',
  'Islas Marshall': 'MH',
  'Isla Mauricio': 'MU',
  Mauritania: 'MR',
  México: 'MX',
  Micronesia: 'FM',
  Moldavia: 'MD',
  Mónaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Mozambique: 'MZ',
  'Myanmar - Birmania': 'MM',
  Namibia: 'NA',
  Nepal: 'NP',
  Nicaragua: 'NI',
  Níger: 'NE',
  Nigeria: 'NG',
  Noruega: 'NO',
  'Nueva Zelanda': 'NZ',
  Omán: 'OM',
  'Países Bajos (Holanda)': 'NL',
  Palau: 'PW',
  Palestina: 'PS',
  Panamá: 'PA',
  'Papuasia Nueva Guinea': 'PG',
  Paquistán: 'PK',
  Paraguay: 'PY',
  Perú: 'PE',
  Polonia: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Reino Unido': 'GB',
  'Rep. Árabe Saharaui Democrática': 'EH',
  'Rep. Centroafricana': 'CF',
  'Rep. Dominicana': 'DO',
  'República Checa': 'CZ',
  'República del Congo': 'CD',
  Ruanda: 'RW',
  Rumanía: 'RO',
  Rusia: 'RU',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Santo Tomé y Príncipe': 'ST',
  Senegal: 'SN',
  Serbia: 'RS',
  'Serbia y Montenegro': 'RR',
  Seychelles: 'SC',
  'Sierra Leona': 'SL',
  Singapur: 'SG',
  Siria: 'SY',
  Somalia: 'SO',
  'Sri Lanka': 'LK',
  Sudáfrica: 'ZA',
  Sudán: 'SD',
  'Sudán del Sur': 'SS',
  Suecia: 'SE',
  Suiza: 'CH',
  Surinam: 'SR',
  Swazilandia: 'SZ',
  Tailandia: 'TH',
  Taiwán: 'TW',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  'Timor Oriental': 'TL',
  Togo: 'TG',
  'Trinidad y Tobago': 'TT',
  Túnez: 'TN',
  Turkmenistán: 'TM',
  Turquía: 'TR',
  Ucrania: 'UA',
  Uganda: 'UG',
  'Unión Soviética': 'ZY',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Yemen: 'YE',
  Yugoslavia: 'YU',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
};
